/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conjuntos;

import com.google.common.collect.Lists;
import com.google.common.collect.Sets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author jse
 */
public class setsform extends javax.swing.JFrame {

    String resultado, r;
    List<String> arreglo4;
    String[] universo={"0","1","2","3","4","5","6","7","8","9"};
    Pattern jdk=Pattern.compile("^[0-9](,[0-9])*$",Pattern.CASE_INSENSITIVE);
    Set<String> setU = new HashSet<String>(Lists.newArrayList(universo));
    /**
     * Creates new form setsform
     */
    public setsform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtl1 = new rojeru_san.rsfield.RSTextFullRound();
        txtl2 = new rojeru_san.rsfield.RSTextFullRound();
        txtl3 = new rojeru_san.rsfield.RSTextFullRound();
        combol1 = new rojerusan.RSComboMetro();
        combol2 = new rojerusan.RSComboMetro();
        comboop = new rojerusan.RSComboMetro();
        switchu = new rojerusan.RSSwitch();
        jLabel5 = new javax.swing.JLabel();
        txtop = new rojeru_san.rsfield.RSTextFullRound();
        jLabel6 = new javax.swing.JLabel();
        txtresultado = new rojeru_san.rsfield.RSTextFullRound();
        jLabel7 = new javax.swing.JLabel();
        btncalcular = new rojerusan.RSButtonIconI();
        jLabel8 = new javax.swing.JLabel();
        rSTextFullRound1 = new rojeru_san.rsfield.RSTextFullRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(0, 91, 160));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(102, 156, 198));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lenguajes y automatas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("L1:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("L2:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("L3:");

        txtl1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtl1ActionPerformed(evt);
            }
        });

        txtl2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        txtl3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtl3ActionPerformed(evt);
            }
        });

        combol1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  -", "L1", "L2", "L3", "R" }));
        combol1.setColorFondo(new java.awt.Color(0, 134, 237));
        combol1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N

        combol2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  -", "L1", "L2", "L3", "R" }));
        combol2.setColorFondo(new java.awt.Color(0, 134, 237));
        combol2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N

        comboop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "U", "∩", "-", "Δ", "X", "'", "+", "*" }));
        comboop.setColorFondo(new java.awt.Color(0, 134, 237));
        comboop.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        comboop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboopActionPerformed(evt);
            }
        });

        switchu.setActivado(false);
        switchu.setColorFondoActivado(new java.awt.Color(74, 210, 97));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("U:");

        txtop.setEnabled(false);
        txtop.setPlaceholder("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Operación:");

        txtresultado.setPlaceholder("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Resultado:");

        btncalcular.setBackground(new java.awt.Color(59, 168, 77));
        btncalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conjuntos/calculate.png"))); // NOI18N
        btncalcular.setText("Calcular");
        btncalcular.setColorHover(new java.awt.Color(110, 219, 128));
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("R: Resultado de la operación anterior");

        rSTextFullRound1.setPlaceholder("Opcional....");

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(switchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                        .addComponent(combol1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboop, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(combol2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rSTextFullRound1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rSPanelGradiente1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtop, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btncalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))))
                .addGap(69, 69, 69))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addComponent(switchu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtl1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtl2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtl3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addComponent(rSTextFullRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combol1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combol2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        Set<String> setA = null;

        Set<String> setB = null;
        Set<String> setC = null;

        txtop.setText("");
        if (txtresultado.getText().isEmpty() == false) {
            resultado = txtresultado.getText().substring(1, txtresultado.getText().length() - 1).replaceAll(" ", "");

            String[] atemp = resultado.split(",");
            arreglo4 = Lists.newArrayList(atemp);
            System.out.println(arreglo4.toString());
        }
        txtresultado.setText("");

        if (switchu.isActivado() == true) {

        } else {
            String c1 = txtl1.getText();
            String c2 = txtl2.getText();
            String c3 = txtl3.getText();
            String[] a1 = c1.split(",");
            String[] a2 = c2.split(",");
            String[] a3 = c3.split(",");

            List<String> arreglo = new ArrayList<String>();
            List<String> arreglo2 = new ArrayList<String>();
            List<String> arreglo3 = new ArrayList<String>();

            arreglo = Lists.newArrayList(a1);
            arreglo2 = Lists.newArrayList(a2);
            arreglo3 = Lists.newArrayList(a3);

            if (String.valueOf(combol1.getSelectedItem()).equals("L1")) {
                setA = new HashSet<String>(arreglo);

                if (String.valueOf(combol2.getSelectedItem()).equals("L2")) {
                    setB = new HashSet<String>(arreglo2);
                }
                if (String.valueOf(combol2.getSelectedItem()).equals("L3")) {
                    setB = new HashSet<String>(arreglo3);
                }
                if (String.valueOf(combol2.getSelectedItem()).equals("R")) {
                    setB = new HashSet<String>(arreglo4);
                }
            } else if (String.valueOf(combol1.getSelectedItem()).equals("L2")) {
                setA = new HashSet<String>(arreglo2);
                if (String.valueOf(combol2.getSelectedItem()).equals("L1")) {
                    setB = new HashSet<String>(arreglo);
                }
                if (String.valueOf(combol2.getSelectedItem()).equals("L3")) {
                    setB = new HashSet<String>(arreglo3);
                }
                if (String.valueOf(combol2.getSelectedItem()).equals("R")) {
                    setB = new HashSet<String>(arreglo4);
                }
            }else if (String.valueOf(combol1.getSelectedItem()).equals("L3")) {
                setA = new HashSet<String>(arreglo3);
                if (String.valueOf(combol2.getSelectedItem()).equals("L1")) {
                    setB = new HashSet<String>(arreglo);
                }
                if (String.valueOf(combol2.getSelectedItem()).equals("L2")) {
                    setB = new HashSet<String>(arreglo2);
                }
                if (String.valueOf(combol2.getSelectedItem()).equals("R")) {
                    setB = new HashSet<String>(arreglo4);
                }
            }else if (String.valueOf(combol1.getSelectedItem()).equals("R")) {
                setA = new HashSet<String>(arreglo4);
                if (String.valueOf(combol2.getSelectedItem()).equals("L1")) {
                    setB = new HashSet<String>(arreglo);
                }
                if (String.valueOf(combol2.getSelectedItem()).equals("L2")) {
                    setB = new HashSet<String>(arreglo2);
                }
                if (String.valueOf(combol2.getSelectedItem()).equals("L3")) {
                    setB = new HashSet<String>(arreglo3);
                }
            }
            txtop.setText("");
            if (String.valueOf(combol2.getSelectedItem()).equals("  -")) {
                txtop.setText(String.valueOf(combol1.getSelectedItem()) + String.valueOf(comboop.getSelectedItem()));
            }else{
                txtop.setText(String.valueOf(combol1.getSelectedItem()) + String.valueOf(comboop.getSelectedItem()) + String.valueOf(combol2.getSelectedItem()));
            }
            

            switch (String.valueOf(comboop.getSelectedItem())) {
                case "U":
                Set<String> unionset = Sets.union(setA, setB);

                r = unionset.toString().replace('[', '{').replace(']', '}');
                txtresultado.setText(r);

                break;

                case "∩":
                Set<String> interset = Sets.intersection(setA, setB);

                r = interset.toString().replace('[', '{').replace(']', '}');
                txtresultado.setText(r);
                break;

                case "-":
                Set<String> diffset = Sets.difference(setA, setB);

                r = diffset.toString().replace('[', '{').replace(']', '}');
                txtresultado.setText(r);
                break;
                case "Δ":
                Set<String> diffsimset = Sets.symmetricDifference(setA, setB);
                r = diffsimset.toString().replace('[', '{').replace(']', '}');
                txtresultado.setText(r);
                break;
                case "X":
                ArrayList<String> cp1=Lists.newArrayList(setA);
                ArrayList<String> cp2=Lists.newArrayList(setB);
                String temp="";
                for (int i = 0; i < cp1.size(); i++) {
                    for (int j = 0; j < cp2.size(); j++) {
                        temp=temp+cp1.get(i)+cp2.get(j)+",";
                    }
                }
                temp="{"+temp.substring(0,temp.length()-1)+"}";

                txtresultado.setText(temp);
                break;
                case "'":
                Set<String> diffset2 = Sets.difference(setU, setA);

                r = diffset2.toString().replace('[', '{').replace(']', '}');
                txtresultado.setText(r);
                break;
                case "+":
                      cp1=Lists.newArrayList(setA);
                 cp2=Lists.newArrayList(setA);
                    String preset =setA.toString().substring(1, setA.toString().length()- 1).replaceAll(" ", "");                 
                    
                 Set<String> sks=null;
                 List<String> aux = null;
                 String aux2[]=null;
                temp="";
                String ks=null;
                    for (int x = 0; x < 1; x++) {
                        for (int i = 0; i < cp1.size(); i++) {
                    for (int j = 0; j < cp2.size(); j++) {
                        
                        temp=temp+cp1.get(i)+cp2.get(j)+",";

                        
                        }
                    }
                ks=temp.substring(0,temp.length()-1);
               aux2=ks.split(",");
               aux=Lists.newArrayList(aux2);
               cp2=Lists.newArrayList(aux);               
                    }
                

                txtresultado.setText("{"+preset+","+ks+"}");
                    
                break;
                case "*":
                     cp1=Lists.newArrayList(setA);
                 cp2=Lists.newArrayList(setA);
                     preset =setA.toString().substring(1, setA.toString().length() - 1).replaceAll(" ", "");                 
                    
                  sks=null;
                  aux = null;
                 aux2=null;
                temp="";
                 ks=null;
                    for (int x = 0; x < 1; x++) {
                        for (int i = 0; i < cp1.size(); i++) {
                    for (int j = 0; j < cp2.size(); j++) {
                        
                        temp=temp+cp1.get(i)+cp2.get(j)+",";

                        
                        }
                    }
                ks=temp.substring(0,temp.length()-1);
               aux2=ks.split(",");
               aux=Lists.newArrayList(aux2);
               cp2=Lists.newArrayList(aux);
               

               
                    }
                
String mostrar="{"+"ε"+","+preset+","+ks+"}";
String mostrar2="ε"+","+preset+","+ks;

String[] amostrar=mostrar2.split(",");

List<String> mostrarsort=Lists.newArrayList(amostrar);
Collections.sort(mostrarsort);
                    System.out.println(mostrarsort.toString());
                txtresultado.setText(mostrar);
                    
                    break;
            }

        }
        combol1.setSelectedIndex(0);
        combol2.setSelectedIndex(0);
        comboop.setSelectedIndex(0);
    }//GEN-LAST:event_btncalcularActionPerformed

    private void comboopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboopActionPerformed

    private void txtl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtl3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtl3ActionPerformed

    private void txtl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtl1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setsform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setsform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI btncalcular;
    private rojerusan.RSComboMetro combol1;
    private rojerusan.RSComboMetro combol2;
    private rojerusan.RSComboMetro comboop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rojeru_san.rsfield.RSTextFullRound rSTextFullRound1;
    private rojerusan.RSSwitch switchu;
    private rojeru_san.rsfield.RSTextFullRound txtl1;
    private rojeru_san.rsfield.RSTextFullRound txtl2;
    private rojeru_san.rsfield.RSTextFullRound txtl3;
    private rojeru_san.rsfield.RSTextFullRound txtop;
    private rojeru_san.rsfield.RSTextFullRound txtresultado;
    // End of variables declaration//GEN-END:variables
}
